/* ===== Phần 5b: Trends — ổn định, trạng từ, cụm Band 7 ===== */
VOCAB.push(
{id:"remain-stable", w:"remain stable", vn:"giữ ổn định", sec:5, sub:"➡️ Ổn định & dao động", s:[
"The figure *remained stable* at around 40% for the rest of the period.",
"Unemployment *remained stable* despite the economic slowdown.",
"Prices *remained stable* between 2010 and 2015.",
"The rural population *remained stable* while cities grew rapidly.",
"After the initial rise, sales *remained stable* for several years.",
"The birth rate *remained stable* at 1.8 children per woman.",
"Demand for gas *remained* relatively *stable* throughout the decade.",
"The proportion of cyclists *remained stable*, at roughly 5%.",
"Interest rates *remained stable* until the crisis of 2008.",
"The company's market share *remained stable* despite new competitors."]},

{id:"remain-unchanged", w:"remain unchanged", vn:"không thay đổi", sec:5, sub:"➡️ Ổn định & dao động", s:[
"The figure for men *remained unchanged* at 55%.",
"Ticket prices *remained unchanged* for over a decade.",
"The pattern *remained unchanged* despite government campaigns.",
"Spending on education *remained* virtually *unchanged* over the period.",
"The ranking of the four countries *remained unchanged* throughout.",
"Average working hours *remained unchanged* between 2000 and 2010.",
"The overall trend *remained unchanged* even after the new policy.",
"The share of nuclear power *remained unchanged* at 20%.",
"Bus fares *remained unchanged* while train fares doubled.",
"The gap between the two groups *remained* largely *unchanged*."]},

{id:"stay-constant", w:"stay constant", vn:"giữ nguyên, không đổi", sec:5, sub:"➡️ Ổn định & dao động", s:[
"The temperature *stayed constant* at around 22 degrees.",
"The number of employees *stayed constant* despite rising output.",
"The proportion of female students *stayed constant* at about half.",
"Rainfall levels *stayed* fairly *constant* from year to year.",
"The price of milk *stayed constant* while other foods became dearer.",
"Demand *stayed constant* even after the advertising campaign ended.",
"The figure *stayed constant* for five years before rising sharply.",
"Membership numbers *stayed constant* at roughly 3,000.",
"The speed of production *stays constant* throughout the process.",
"Energy use per household *stayed constant* thanks to efficiency gains."]},

{id:"level-off", w:"level off", vn:"chững lại, đi ngang", sec:5, sub:"➡️ Ổn định & dao động", s:[
"After rising sharply, the figure *levelled off* at around 70%.",
"Sales grew quickly at first but *levelled off* after 2015.",
"The population increased for decades before *levelling off*.",
"Prices *levelled off* once the shortage ended.",
"The line climbs steeply and then *levels off* towards the end.",
"Growth *levelled off* as the market became saturated.",
"Smartphone ownership *levelled off* at about 90% of adults.",
"The unemployment rate *levelled off* following two years of decline.",
"Demand for the product *levelled off* after the initial excitement.",
"Temperatures rise all morning and *level off* in the early afternoon."]},

{id:"stabilize-at", w:"stabilize at", vn:"ổn định ở mức", sec:5, sub:"➡️ Ổn định & dao động", s:[
"The figure eventually *stabilized at* around 30%.",
"After wild fluctuations, oil prices *stabilized at* $70 a barrel.",
"The exchange rate *stabilized at* 1.2 dollars to the euro.",
"Enrolment *stabilized at* roughly 5,000 students per year.",
"The birth rate *stabilized at* 1.6 children per woman after 2010.",
"Inflation finally *stabilized at* 2% following the reforms.",
"Visitor numbers *stabilized at* pre-crisis levels by 2023.",
"The company's market share *stabilized at* about a quarter.",
"Water levels in the lake *stabilized at* a much lower point.",
"After the boom years, growth *stabilized at* 3% annually."]},

{id:"fluctuate", w:"fluctuate", vn:"dao động, biến động", sec:5, sub:"➡️ Ổn định & dao động", s:[
"The figure *fluctuated* between 20% and 30% throughout the period.",
"Oil prices *fluctuated* wildly during the crisis.",
"Sales *fluctuated* from month to month but showed no clear trend.",
"The temperature *fluctuates* considerably between day and night.",
"Visitor numbers *fluctuated* seasonally, peaking each summer.",
"The exchange rate *fluctuated* before settling at a stable level.",
"There were noticeable *fluctuations* in the unemployment rate.",
"The company's profits *fluctuated* in line with fuel costs.",
"Rainfall *fluctuated* significantly from one year to the next.",
"After 2010, the figure *fluctuated* only slightly around 50%."]},

{id:"slightly", w:"slightly", vn:"hơi, một chút", sec:5, sub:"🎚️ Trạng từ mức độ", s:[
"The figure rose *slightly*, from 22% to 24%.",
"Unemployment fell *slightly* in the final year.",
"Prices were *slightly* higher in the capital than elsewhere.",
"The proportion of male students decreased *slightly* over the decade.",
"Sales dipped *slightly* in the summer months.",
"The average temperature increased *slightly* between 1990 and 2000.",
"Spending on entertainment grew *slightly* faster than incomes.",
"The two figures differed only *slightly* by the end of the period.",
"The birth rate declined *slightly* before stabilising.",
"Demand for gas rose *slightly* while demand for coal collapsed."]},

{id:"marginally", w:"marginally", vn:"rất ít, không đáng kể", sec:5, sub:"🎚️ Trạng từ mức độ", s:[
"The figure increased only *marginally*, from 15% to 16%.",
"Profits were *marginally* higher than in the previous year.",
"The unemployment rate fell *marginally* in 2018.",
"Rural incomes grew *marginally* while urban incomes soared.",
"The cost of living rose *marginally* faster than wages.",
"Attendance improved *marginally* after the ticket price cut.",
"The share of renewable energy expanded only *marginally* before 2005.",
"Women's average salaries increased *marginally* over the period.",
"The figure for cycling changed only *marginally* in twenty years.",
"Exports declined *marginally* but remained well above imports."]},

{id:"gradually", w:"gradually", vn:"dần dần, từ từ", sec:5, sub:"🎚️ Trạng từ mức độ", s:[
"The population increased *gradually*, reaching five million by 2020.",
"Coal use declined *gradually* as cleaner fuels took over.",
"The figure climbed *gradually* from 30% to 45%.",
"House prices rose *gradually* throughout the 1990s.",
"The gap between the two countries narrowed *gradually*.",
"Smoking rates fell *gradually* after the ban was introduced.",
"The town expanded *gradually* along the new railway line.",
"Interest in the subject grew *gradually* over the decade.",
"Temperatures rise *gradually* from March to July.",
"The old industrial areas were *gradually* replaced by housing."]},

{id:"steadily", w:"steadily", vn:"đều đặn, ổn định", sec:5, sub:"🎚️ Trạng từ mức độ", s:[
"The number of internet users grew *steadily* from 2000 onwards.",
"Life expectancy increased *steadily* in all four countries.",
"Sales rose *steadily*, doubling by the end of the period.",
"The proportion of working women climbed *steadily* after 1980.",
"Exports expanded *steadily* at around 5% per year.",
"The figure declined *steadily*, losing two points every year.",
"University enrolment grew *steadily* throughout the decade.",
"The market share of electric cars is rising *steadily*.",
"Rents increased *steadily* while wages barely moved.",
"Recycling rates improved *steadily* thanks to the new scheme."]},

{id:"moderately", w:"moderately", vn:"vừa phải", sec:5, sub:"🎚️ Trạng từ mức độ", s:[
"The figure grew *moderately*, from 40% to 48%.",
"Prices increased *moderately* compared with the previous decade.",
"Demand rose *moderately* during the spring months.",
"The economy expanded *moderately* at around 2% a year.",
"Spending on leisure increased *moderately* as incomes rose.",
"The unemployment rate improved *moderately* after the reforms.",
"Attendance grew *moderately* despite the poor weather.",
"The cost of housing rose *moderately* outside the capital.",
"Energy consumption fell *moderately* thanks to new technology.",
"Sales performed *moderately* well in the first quarter."]},

{id:"considerably", w:"considerably", vn:"đáng kể", sec:5, sub:"🎚️ Trạng từ mức độ", s:[
"The figure rose *considerably*, from 4% to over 8%.",
"Living standards improved *considerably* during the boom years.",
"The number of tourists increased *considerably* after the airport opened.",
"Spending on technology grew *considerably* in the final decade.",
"The gap between rich and poor widened *considerably*.",
"House prices fell *considerably* following the crash.",
"The proportion of graduates rose *considerably* in all regions.",
"Travel times were reduced *considerably* by the new motorway.",
"The figure for renewable energy expanded *considerably* after 2010.",
"Average incomes differed *considerably* between the two cities."]},

{id:"significantly", w:"significantly", vn:"đáng kể, rõ rệt", sec:5, sub:"🎚️ Trạng từ mức độ", s:[
"The number of car owners increased *significantly* between 1990 and 2010.",
"Unemployment fell *significantly* after the new policy was introduced.",
"The figure for online sales rose *significantly*, reaching 60%.",
"Air quality improved *significantly* once the factories closed.",
"Spending on defence declined *significantly* after the war.",
"The proportion of elderly residents grew *significantly* over the period.",
"Prices vary *significantly* between the north and the south.",
"Attendance dropped *significantly* when the entrance fee doubled.",
"The literacy rate improved *significantly* in rural areas.",
"Exports contributed *significantly* more to GDP than before."]},

{id:"dramatically", w:"dramatically", vn:"mạnh mẽ, kịch tính", sec:5, sub:"🎚️ Trạng từ mức độ", s:[
"The number of smartphone users rose *dramatically* after 2007.",
"Sales fell *dramatically* during the recession.",
"The city's skyline changed *dramatically* over thirty years.",
"Fuel prices increased *dramatically* following the conflict.",
"The birth rate dropped *dramatically* in the 1970s.",
"Internet speeds improved *dramatically* within a decade.",
"The figure surged *dramatically*, tripling in five years.",
"Cinema attendance declined *dramatically* with the rise of streaming.",
"The company's fortunes changed *dramatically* after the takeover.",
"Demand for air travel grew *dramatically* between 1990 and 2019."]},

{id:"sharply", w:"sharply", vn:"đột ngột, mạnh", sec:5, sub:"🎚️ Trạng từ mức độ", s:[
"The figure fell *sharply* between 2008 and 2009.",
"Prices rose *sharply* in the first quarter of the year.",
"The unemployment rate climbed *sharply* during the crisis.",
"Exports dropped *sharply* when the trade deal collapsed.",
"The line rises *sharply* before flattening out after 2015.",
"Interest in the course increased *sharply* after it moved online.",
"Sales of diesel cars declined *sharply* following the scandal.",
"The temperature drops *sharply* at night in the desert.",
"The number of applicants rose *sharply* once fees were abolished.",
"Profits fell *sharply*, hitting their lowest level in a decade."]},

{id:"rapidly", w:"rapidly", vn:"nhanh chóng", sec:5, sub:"🎚️ Trạng từ mức độ", s:[
"The city's population grew *rapidly* after the war.",
"Internet access spread *rapidly* across the developing world.",
"The figure increased *rapidly*, doubling in just three years.",
"Sales of electric vehicles are rising *rapidly*.",
"The industry expanded *rapidly* thanks to foreign investment.",
"Prices rose *rapidly* during the shortage.",
"The gap between the two figures widened *rapidly* after 2010.",
"Demand for online courses grew *rapidly* during the lockdown.",
"The forest area shrank *rapidly* due to logging.",
"Technology is changing consumer habits *rapidly*."]},

{id:"experience-increase", w:"experience an increase", vn:"trải qua sự tăng", sec:5, sub:"⭐ Cụm Band 7", s:[
"The country *experienced a* sharp *increase* in tourism after 2010.",
"Both cities *experienced an increase* in population over the period.",
"The sector *experienced a* significant *increase* in investment.",
"Rural areas *experienced a* modest *increase* in internet access.",
"The company *experienced an increase* in sales of almost 20%.",
"All age groups *experienced an increase* in life expectancy.",
"The region *experienced a* dramatic *increase* in house prices.",
"Public transport *experienced an increase* in passenger numbers.",
"The university *experienced a* steady *increase* in overseas applications.",
"Exports *experienced a* considerable *increase* in the final decade."]},

{id:"witness-rise", w:"witness a rise", vn:"chứng kiến sự tăng", sec:5, sub:"⭐ Cụm Band 7", s:[
"The period *witnessed a* dramatic *rise* in oil prices.",
"The 1990s *witnessed a* steady *rise* in car ownership.",
"The country *witnessed a* sharp *rise* in unemployment during the crisis.",
"Recent years have *witnessed a rise* in remote working.",
"The city *witnessed a* rapid *rise* in property values.",
"The decade *witnessed a* significant *rise* in university enrolment.",
"The market *witnessed a* sudden *rise* in demand for electric cars.",
"The industry *witnessed a* gradual *rise* in female employment.",
"The final years of the period *witnessed a rise* in exports.",
"Both charts *witnessed a rise* in the use of renewable energy."]},

{id:"upward-trend", w:"show an upward trend", vn:"có xu hướng tăng", sec:5, sub:"⭐ Cụm Band 7", s:[
"The figures for all three countries *showed an upward trend*.",
"Sales *showed a* clear *upward trend* throughout the decade.",
"The graph *shows an upward trend* in average temperatures.",
"Tourist arrivals *showed a* steady *upward trend* after 2005.",
"Despite monthly fluctuations, the overall pattern *showed an upward trend*.",
"House prices *showed an upward trend* in every region.",
"The data *show a* strong *upward trend* in online shopping.",
"Female participation in sport *showed an upward trend* over the period.",
"Energy consumption *showed an upward trend* until the 2008 crisis.",
"The chart *shows a* consistent *upward trend* in life expectancy."]},

{id:"downward-trend", w:"show a downward trend", vn:"có xu hướng giảm", sec:5, sub:"⭐ Cụm Band 7", s:[
"Cinema attendance *showed a downward trend* from 1960 onwards.",
"The figures for smoking *showed a* clear *downward trend*.",
"The graph *shows a downward trend* in manufacturing jobs.",
"Newspaper sales *showed a* steady *downward trend* throughout the period.",
"Despite occasional peaks, the overall pattern *showed a downward trend*.",
"The birth rate *showed a downward trend* in all developed countries.",
"Coal consumption *showed a* marked *downward trend* after 2010.",
"The data *show a downward trend* in teenage unemployment.",
"Landline ownership *showed a downward trend* as mobiles spread.",
"The chart *shows a* gradual *downward trend* in household size."]}
);
