/* ===== Phần 1: Overview & Introduction ===== */
VOCAB.push(
{id:"overall", w:"Overall,", vn:"Nhìn chung", sec:1, sub:"Mở đầu phần Overview", s:[
"*Overall,* the number of internet users increased significantly over the period.",
"*Overall,* car ownership in both countries showed an upward trend between 1990 and 2010.",
"*Overall,* petrol remained the most popular type of fuel throughout the period.",
"*Overall,* the proportion of people living in cities grew steadily in all three regions.",
"*Overall,* coffee consumption rose in Europe, whereas tea consumption declined.",
"*Overall,* the figures for unemployment fluctuated but ended lower than they began.",
"*Overall,* it can be seen that renewable energy became far more important after 2005.",
"*Overall,* men spent more time on sport than women in every age group.",
"*Overall,* the birth rate fell in most developed countries during this period.",
"*Overall,* spending on education accounted for the largest share of the budget."]},

{id:"in-general", w:"In general,", vn:"Nhìn chung", sec:1, sub:"Mở đầu phần Overview", s:[
"*In general,* the amount of waste recycled increased in all four cities.",
"*In general,* older people watched more television than younger people.",
"*In general,* the trend for cinema attendance was upward despite some fluctuations.",
"*In general,* exports grew faster than imports over the twenty-year period.",
"*In general,* the two charts show a clear shift towards online shopping.",
"*In general,* electricity consumption was higher in winter than in summer.",
"*In general,* women were more likely to work part-time than men.",
"*In general,* the proportion of students studying abroad rose in every country shown.",
"*In general,* meat consumption declined while demand for vegetables increased.",
"*In general,* larger households spent a smaller share of their income on food."]},

{id:"generally", w:"Generally,", vn:"Nói chung", sec:1, sub:"Mở đầu phần Overview", s:[
"*Generally,* the population of the town grew steadily between 1950 and 2000.",
"*Generally,* people in rural areas relied more heavily on private cars.",
"*Generally,* the sales figures improved in the second half of the year.",
"*Generally,* young adults used social media far more often than older groups.",
"*Generally,* the price of housing rose faster than average incomes.",
"*Generally,* both companies experienced growth, although at different rates.",
"*Generally,* the number of visitors was highest during the summer months.",
"*Generally,* the amount of time spent cooking at home decreased over the period.",
"*Generally,* developed countries produced more waste per person than developing ones.",
"*Generally,* the demand for air travel showed a strong upward trend."]},

{id:"notably", w:"Notably,", vn:"Đáng chú ý là", sec:1, sub:"Mở đầu phần Overview", s:[
"*Notably,* the figure for Japan more than doubled during the period.",
"*Notably,* sales of electric cars overtook those of diesel cars in 2018.",
"*Notably,* the unemployment rate reached its lowest point in 2007.",
"*Notably,* only one age group showed a decrease in exercise levels.",
"*Notably,* spending on entertainment was twice as high as spending on books.",
"*Notably,* the gap between male and female graduates narrowed considerably.",
"*Notably,* China accounted for nearly half of global production by 2015.",
"*Notably,* the smallest category at the start became the largest by the end.",
"*Notably,* internet usage grew fastest among people aged over 65.",
"*Notably,* the trend reversed sharply after the year 2000."]},

{id:"it-is-clear-that", w:"It is clear that", vn:"Rõ ràng là", sec:1, sub:"Mở đầu phần Overview", s:[
"*It is clear that* the demand for renewable energy rose dramatically over the period.",
"*It is clear that* young people preferred streaming services to traditional television.",
"*It is clear that* the two countries followed very different trends.",
"*It is clear that* tourism became the city's main source of income.",
"*It is clear that* the proportion of smokers fell in every age group.",
"*It is clear that* online sales grew at the expense of high-street shopping.",
"*It is clear that* the factory's output peaked in 2010 before declining.",
"*It is clear that* households spent more on transport than on any other category.",
"*It is clear that* literacy rates improved significantly in all regions shown.",
"*It is clear that* the gap between rich and poor areas widened over time."]},

{id:"readily-apparent", w:"It is readily apparent that", vn:"Có thể dễ dàng nhận thấy rằng", sec:1, sub:"Mở đầu phần Overview", s:[
"*It is readily apparent that* car use increased in all five cities.",
"*It is readily apparent that* the service sector dominated the economy by 2020.",
"*It is readily apparent that* fewer people chose to study languages at university.",
"*It is readily apparent that* the overall trend for both charts was upward.",
"*It is readily apparent that* women outnumbered men in part-time employment.",
"*It is readily apparent that* the coldest months attracted the fewest tourists.",
"*It is readily apparent that* recycling rates varied widely between the four countries.",
"*It is readily apparent that* the company's profits depended heavily on exports.",
"*It is readily apparent that* mobile phones replaced landlines as the main form of communication.",
"*It is readily apparent that* energy consumption per person was highest in the United States."]},

{id:"evident", w:"It is evident that", vn:"Rõ ràng rằng", sec:1, sub:"Mở đầu phần Overview", s:[
"*It is evident that* the population aged 65 and over grew fastest.",
"*It is evident that* public transport became more popular after ticket prices fell.",
"*It is evident that* the majority of students preferred to live on campus.",
"*It is evident that* fast food consumption rose sharply among teenagers.",
"*It is evident that* the region's rainfall decreased steadily over the decade.",
"*It is evident that* both figures followed a similar pattern until 2005.",
"*It is evident that* domestic flights lost passengers to high-speed rail.",
"*It is evident that* the highest earners spent the smallest proportion on food.",
"*It is evident that* investment in technology brought clear benefits to the company.",
"*It is evident that* the differences between the two groups became smaller over time."]},

{id:"throughout-period", w:"throughout the period", vn:"trong suốt giai đoạn", sec:1, sub:"Mở đầu phần Overview", s:[
"Petrol remained the most common fuel *throughout the period*.",
"The birth rate stayed relatively stable *throughout the period* shown.",
"*Throughout the period*, the USA was the largest producer of corn.",
"Unemployment fluctuated between 5% and 8% *throughout the period*.",
"Rice was the main export of the country *throughout the period*.",
"*Throughout the period*, women earned less than men on average.",
"The city's population continued to grow *throughout the period* in question.",
"Demand for electricity rose almost continuously *throughout the period*.",
"*Throughout the period*, the north of the country received more rainfall than the south.",
"Sales of printed newspapers declined steadily *throughout the period*."]},

{id:"illustrate", w:"illustrate", vn:"minh họa", sec:1, sub:"Động từ cho câu Introduction", s:[
"The bar chart *illustrates* the proportion of household income spent on food.",
"The two graphs *illustrate* changes in car ownership between 1990 and 2020.",
"The diagram *illustrates* the process by which glass bottles are recycled.",
"The table *illustrates* the number of overseas students in four English-speaking countries.",
"The line graph *illustrates* how coffee consumption changed over three decades.",
"The pie charts *illustrate* the main sources of energy in 1980 and 2010.",
"The map *illustrates* the development of the town since 1950.",
"The chart *illustrates* differences in exercise habits between men and women.",
"The graph *illustrates* fluctuations in the unemployment rate over ten years.",
"The figures *illustrate* a clear shift from rural to urban living."]},

{id:"compare", w:"compare", vn:"so sánh", sec:1, sub:"Động từ cho câu Introduction", s:[
"The bar chart *compares* the populations of five European capital cities.",
"The graphs *compare* internet usage in developed and developing countries.",
"The table *compares* average working hours across six different nations.",
"The charts *compare* household spending in 1995 and 2015.",
"The diagram *compares* two methods of generating electricity.",
"The figures *compare* male and female participation in higher education.",
"The pie charts *compare* the market shares of four smartphone brands.",
"The line graph *compares* birth rates in three Asian countries.",
"The maps *compare* the town centre before and after redevelopment.",
"The data *compare* levels of car ownership among different income groups."]},

{id:"show", w:"show", vn:"cho thấy", sec:1, sub:"Động từ cho câu Introduction", s:[
"The graph *shows* the number of tourists visiting Thailand each year.",
"The chart *shows* how much time teenagers spend on different activities.",
"The table *shows* the results of a survey on shopping habits.",
"The figures *show* a steady rise in life expectancy over the century.",
"The two pie charts *show* the composition of household waste in 2000 and 2020.",
"The diagram *shows* the stages involved in producing chocolate.",
"The map *shows* the proposed changes to the city's transport network.",
"The data *show* that most journeys to work were made by car.",
"The line graph *shows* fluctuations in oil prices between 2005 and 2015.",
"The bar chart *shows* the percentage of adults who exercise regularly."]},

{id:"present", w:"present", vn:"trình bày", sec:1, sub:"Động từ cho câu Introduction", s:[
"The table *presents* data on average rainfall in four Australian cities.",
"The chart *presents* information about the ages of first-time home buyers.",
"The graphs *present* trends in energy production over a fifty-year period.",
"The diagram *presents* the life cycle of a salmon.",
"The figures *present* a detailed picture of changing eating habits.",
"The bar chart *presents* the results of a customer satisfaction survey.",
"The two charts *present* employment figures for men and women separately.",
"The map *presents* an overview of the island's main tourist attractions.",
"The data *present* a comparison of literacy rates across five regions.",
"The pie chart *presents* the proportion of the budget allocated to each department."]},

{id:"depict", w:"depict", vn:"mô tả (bằng hình ảnh)", sec:1, sub:"Động từ cho câu Introduction", s:[
"The line graph *depicts* changes in average house prices since 1990.",
"The chart *depicts* the amount of fast food consumed in three countries.",
"The maps *depict* the village of Stokeford in 1930 and 2010.",
"The diagram *depicts* how rainwater is collected and reused.",
"The graph *depicts* a sharp rise in smartphone ownership after 2007.",
"The figures *depict* a gradual decline in cinema attendance.",
"The bar chart *depicts* differences in salary between five professions.",
"The pie charts *depict* the sources of government revenue in two separate years.",
"The table *depicts* the number of hours students spend studying each week.",
"The illustration *depicts* the process of manufacturing paper from wood."]},

{id:"indicate", w:"indicate", vn:"chỉ ra", sec:1, sub:"Động từ cho câu Introduction", s:[
"The figures *indicate* a strong preference for online banking among young adults.",
"The graph *indicates* that sales peaked during the holiday season.",
"The data *indicate* a close link between income and car ownership.",
"The chart *indicates* how the market changed after 2010.",
"The results *indicate* that most respondents supported the new policy.",
"The table *indicates* the average temperatures recorded in each month.",
"The trend line *indicates* a gradual recovery in the housing market.",
"The statistics *indicate* that fewer people smoked in 2020 than in 2000.",
"The survey results *indicate* growing concern about air pollution.",
"The two charts *indicate* a clear change in consumer behaviour."]},

{id:"demonstrate", w:"demonstrate", vn:"cho thấy rõ", sec:1, sub:"Động từ cho câu Introduction", s:[
"The graph clearly *demonstrates* the impact of the financial crisis on employment.",
"The figures *demonstrate* a growing demand for renewable energy.",
"The chart *demonstrates* how spending patterns differ between age groups.",
"The data *demonstrate* that exports rose steadily throughout the decade.",
"The results *demonstrate* a significant improvement in air quality.",
"The comparison *demonstrates* the advantages of public transport over private cars.",
"The statistics *demonstrate* that tourism recovered quickly after 2021.",
"The table *demonstrates* wide differences in internet access between regions.",
"The trend *demonstrates* the increasing popularity of remote working.",
"The two maps *demonstrate* how much the coastline has changed over fifty years."]}
);
