/* ===== Phần 2: Key Expressions — diễn đạt số liệu ===== */
VOCAB.push(
{id:"account-for", w:"account for", vn:"chiếm (tỷ lệ)", sec:2, s:[
"The IT industry *accounted for* 6% of GDP in 2015.",
"Cars *account for* nearly three-quarters of all journeys to work.",
"In 1990, coal *accounted for* the largest share of electricity production.",
"Women *accounted for* 65% of part-time workers in the country.",
"Housing costs *account for* about a third of the average family's budget.",
"Tourism *accounts for* a significant proportion of the island's income.",
"By 2020, online sales *accounted for* over half of total revenue.",
"Young people aged 18 to 25 *accounted for* most social media users.",
"Agriculture *accounted for* only 2% of employment by the end of the period.",
"Together, the two companies *account for* 80% of the smartphone market."]},

{id:"stand-at", w:"stand at", vn:"ở mức", sec:2, s:[
"The unemployment rate *stood at* 5% at the beginning of the period.",
"In 2010, the city's population *stood at* just under two million.",
"The figure for car exports *stood at* 40,000 units in the final year.",
"Average house prices *stood at* £150,000 in 1995.",
"The literacy rate *stood at* 92% by the end of the decade.",
"At its lowest point, the birth rate *stood at* only 1.2 children per woman.",
"Coffee consumption *stood at* three kilograms per person per year.",
"The company's profits *stood at* $2 million before the crisis began.",
"In January, visitor numbers *stood at* around 10,000 per month.",
"The proportion of renewable energy *stood at* 15% in 2012."]},

{id:"reach", w:"reach", vn:"đạt (mức)", sec:2, s:[
"The number of internet users *reached* four billion in 2018.",
"By 2005, the figure had *reached* its highest point of the whole period.",
"Sales *reached* a record level of 500,000 units in December.",
"The temperature *reaches* an average of 30 degrees in July.",
"The proportion of graduates *reached* 45% by the end of the period.",
"After rising steadily, oil production *reached* a plateau in 2010.",
"Visitor numbers *reached* one million for the first time in 2019.",
"The unemployment rate *reached* a low of 3% in 2007.",
"Spending on healthcare *reached* 10% of GDP in the final year.",
"The population is expected to *reach* nine billion by 2050."]},

{id:"peak-at", w:"peak at / reach a peak of", vn:"đạt đỉnh", sec:2, s:[
"Sales *peaked at* 80,000 units in 2010 before falling sharply.",
"The birth rate *reached a peak of* 3.5 children per woman in 1965.",
"Unemployment *peaked at* 12% during the recession.",
"Visitor numbers *peak* during the summer months, at around 50,000.",
"The price of oil *reached a peak of* $140 per barrel in 2008.",
"Electricity demand *peaks at* about 6 p.m. on weekdays.",
"The figure for coal production *peaked at* 200 million tonnes in 1990.",
"Cinema attendance *reached a peak of* 1.6 billion visits in 1946.",
"The company's market share *peaked at* 35% before competitors emerged.",
"Traffic volume *peaks at* rush hour, then falls steadily through the evening."]},

{id:"hit", w:"hit", vn:"chạm mức, đạt", sec:2, s:[
"The unemployment rate *hit* 10% during the financial crisis.",
"House prices *hit* an all-time high in 2021.",
"Sales of electric cars *hit* one million units for the first time.",
"The figure *hit* its lowest point in 2003 before recovering.",
"Exports *hit* $50 billion, the highest level ever recorded.",
"Temperatures *hit* 40 degrees during the hottest month.",
"The number of subscribers *hit* the ten-million mark in 2019.",
"Production *hit* a low of 20,000 units during the strike.",
"By June, visitor numbers had *hit* record levels.",
"The company's share price *hit* rock bottom before the takeover."]},

{id:"finish-at", w:"finish at / end at", vn:"kết thúc ở mức", sec:2, s:[
"The figure rose steadily and *finished at* 75% in 2020.",
"After several fluctuations, the price *ended at* $90 per barrel.",
"Sales began at 10,000 units and *finished at* almost triple that figure.",
"The unemployment rate *ended* the period *at* just 4%.",
"Despite an early fall, the graph *finishes at* a higher point than it starts.",
"The proportion of smokers *ended at* 15%, half the original figure.",
"Coffee exports *finished* the decade *at* record levels.",
"The line for Japan *ends at* roughly the same level as it began.",
"The company's profits *finished at* $8 million, up from $3 million.",
"Both figures *ended* the period *at* around 60%."]},

{id:"figure-for", w:"the figure for", vn:"số liệu của / con số về", sec:2, s:[
"*The figure for* car ownership doubled between 1990 and 2010.",
"*The figure for* Japan was the highest of all five countries.",
"By contrast, *the figure for* rural areas fell steadily.",
"*The figure for* female employment rose to 60% in 2015.",
"*The figure for* renewable energy remained low throughout the period.",
"In 2000, *the figure for* internet users stood at only 5%.",
"*The figure for* meat consumption was twice as high in the USA as in India.",
"*The figures for* both countries followed a similar upward trend.",
"*The figure for* public transport use dropped after fares increased.",
"Meanwhile, *the figure for* online shopping grew dramatically."]},

{id:"make-up", w:"make up", vn:"chiếm, tạo thành", sec:2, s:[
"Women *made up* the majority of the part-time workforce.",
"Oil and gas *make up* around 60% of the country's exports.",
"Students *made up* nearly half of all cinema visitors.",
"In 1980, agriculture *made up* a quarter of the national economy.",
"Plastic *makes up* the largest proportion of household waste.",
"Foreign tourists *made up* 70% of visitors to the museum.",
"Young adults *make up* the biggest group of social media users.",
"Renewable sources *made up* just 10% of total energy production.",
"Housing and transport together *make up* over half of average spending.",
"By 2020, electric vehicles *made up* one in ten new car sales."]},

{id:"represent", w:"represent", vn:"chiếm, tương ứng với", sec:2, s:[
"This figure *represents* a quarter of the country's total exports.",
"Women *represented* 45% of the workforce by the end of the period.",
"The service sector *represents* the largest part of the economy.",
"These sales *represented* an increase of 20% on the previous year.",
"Tourists from Asia *represent* the fastest-growing group of visitors.",
"Coal *represented* half of all energy production in 1970.",
"The under-25s *represent* a third of the city's population.",
"This amount *represents* a significant rise compared with 2010.",
"Food and drink *represented* the biggest category of household spending.",
"Exports to Europe *represent* 40% of the company's total revenue."]},

{id:"generate", w:"generate", vn:"tạo ra", sec:2, s:[
"Tourism *generated* over $2 billion for the local economy in 2019.",
"The IT sector *generates* more revenue than agriculture and mining combined.",
"Wind farms *generated* 20% of the country's electricity by 2020.",
"Exports of coffee *generate* most of the region's income.",
"The new factory *generated* thousands of jobs for local people.",
"Online advertising *generated* the majority of the company's profits.",
"Hydroelectric dams *generate* clean energy for millions of homes.",
"The festival *generates* significant income for hotels and restaurants.",
"Manufacturing *generated* a smaller share of GDP each year.",
"By 2015, services *generated* three times as much revenue as industry."]},

{id:"contribute-to", w:"contribute to / contribution to GDP", vn:"đóng góp vào (GDP)", sec:2, s:[
"The IT industry's *contribution to GDP* rose from 4% to 8%.",
"Tourism *contributes* significantly *to* the national economy.",
"Agriculture *contributed* less *to* GDP each decade.",
"By 2020, services *contributed* over 70% *to* the country's GDP.",
"The mining sector's *contribution to* exports fell sharply.",
"Small businesses *contribute* around a third *to* total employment.",
"Manufacturing made the largest *contribution to* economic growth in the 1980s.",
"The *contribution* of renewable energy *to* the power supply doubled.",
"Foreign investment *contributed to* the rapid growth of the city.",
"Rising exports *contributed to* a strong increase in national income."]},

{id:"share", w:"share (of GDP)", vn:"tỷ trọng, thị phần", sec:2, s:[
"The *share* of GDP generated by agriculture fell to just 3%.",
"Renewable energy's *share* of total production rose steadily.",
"The company increased its market *share* from 10% to 25%.",
"Housing takes the largest *share* of most families' income.",
"The *share* of women in senior positions grew slowly over the decade.",
"Coal's *share* of electricity generation halved between 1990 and 2020.",
"Online retailers now hold a growing *share* of the market.",
"The service sector's *share* of employment reached 80%.",
"Imports made up an increasing *share* of food consumption.",
"Asia's *share* of global manufacturing rose dramatically."]},

{id:"proportion", w:"proportion", vn:"tỷ lệ", sec:2, s:[
"The *proportion* of people owning smartphones rose to 85%.",
"A large *proportion* of the budget was spent on healthcare.",
"The *proportion* of students studying science fell slightly.",
"Only a small *proportion* of waste was recycled in 1990.",
"The *proportion* of women in the workforce grew considerably.",
"An increasing *proportion* of energy came from renewable sources.",
"The *proportion* of income spent on food declined as earnings rose.",
"Roughly equal *proportions* of men and women attended university.",
"The *proportion* of elderly residents doubled over fifty years.",
"A higher *proportion* of city dwellers used public transport."]},

{id:"percentage", w:"percentage", vn:"phần trăm", sec:2, s:[
"The *percentage* of homes with internet access reached 95%.",
"A small *percentage* of respondents disagreed with the statement.",
"The *percentage* of unemployed young people fell after 2012.",
"What *percentage* of the budget was allocated to education?",
"The *percentage* of overweight adults rose in every country surveyed.",
"A high *percentage* of graduates found work within six months.",
"The *percentage* of car-free households was highest in the capital.",
"The chart shows the *percentage* of income spent on five categories.",
"The *percentage* of flights delayed dropped significantly.",
"Between 2000 and 2010, the *percentage* of smokers fell by ten points."]}
);
