/* ===== Phần 5a: Trends — động từ tăng & giảm ===== */
VOCAB.push(
{id:"increase", w:"increase", vn:"tăng", sec:5, sub:"📈 Động từ TĂNG", s:[
"The number of tourists *increased* from two million to five million.",
"Sales *increased* steadily throughout the decade.",
"The proportion of recycled waste *increased* to 45% by 2020.",
"Spending on healthcare *increased* by 8% in a single year.",
"There was a sharp *increase* in fuel prices after 2008.",
"The population is expected to *increase* by a third by 2050.",
"Internet usage *increased* dramatically among older people.",
"The figure *increased* slightly, from 22% to 24%.",
"Demand for electric cars continues to *increase* year after year.",
"The chart shows a steady *increase* in average life expectancy."]},

{id:"rise", w:"rise", vn:"tăng, tăng lên", sec:5, sub:"📈 Động từ TĂNG", s:[
"The figure *rose* to 15% by the end of the period.",
"House prices *rose* sharply between 2002 and 2007.",
"The number of working women *rose* steadily after 1990.",
"Temperatures *rise* to an average of 28 degrees in summer.",
"There was a significant *rise* in the cost of living.",
"Unemployment *rose* by three percentage points during the recession.",
"The line for gas *rises* gradually before levelling off.",
"Coffee exports *rose* from 50,000 to 120,000 tonnes.",
"Sea levels have *risen* noticeably over the past century.",
"The graph shows a steady *rise* in student numbers."]},

{id:"grow", w:"grow", vn:"tăng trưởng", sec:5, sub:"📈 Động từ TĂNG", s:[
"The economy *grew* by an average of 3% per year.",
"The city's population *grew* rapidly after the new factory opened.",
"Online sales *grew* faster than sales in physical stores.",
"The tourism sector has *grown* into the island's main industry.",
"Demand for organic food *grew* steadily among younger shoppers.",
"The figure *grew* from a mere 5% to almost 30%.",
"Exports *grew* strongly in the final five years of the period.",
"The market for smartphones *grew* enormously between 2007 and 2015.",
"There was strong *growth* in the renewable energy sector.",
"The number of overseas students *grew* threefold over the period."]},

{id:"climb", w:"climb", vn:"tăng dần, leo lên", sec:5, sub:"📈 Động từ TĂNG", s:[
"The figure *climbed* steadily to reach 60% in 2015.",
"Oil prices *climbed* above $100 a barrel for the first time.",
"Attendance *climbed* year by year, peaking in 2019.",
"The unemployment rate *climbed* to 11% during the crisis.",
"Sales *climbed* slowly at first, then accelerated after 2010.",
"The temperature *climbs* rapidly between morning and midday.",
"Profits *climbed* back to their previous level within two years.",
"The number of cyclists *climbed* sharply once the new lanes opened.",
"The line *climbs* gently throughout the first half of the graph.",
"Production *climbed* from 200 to 350 units per day."]},

{id:"jump", w:"jump", vn:"tăng vọt, nhảy vọt", sec:5, sub:"📈 Động từ TĂNG", s:[
"The figure *jumped* from 10% to 25% in just two years.",
"Sales *jumped* dramatically after the product appeared on television.",
"The price of wheat *jumped* by 40% following the drought.",
"Visitor numbers *jumped* during the school holidays.",
"There was a sudden *jump* in electricity demand in the evening.",
"The company's share price *jumped* on news of the merger.",
"Applications *jumped* sharply once the fees were reduced.",
"The unemployment rate *jumped* to 12% within six months.",
"Exports *jumped* to a record high in the final year.",
"The graph shows a noticeable *jump* between 2008 and 2009."]},

{id:"surge", w:"surge", vn:"tăng vọt, dâng cao", sec:5, sub:"📈 Động từ TĂNG", s:[
"Demand for face masks *surged* during the pandemic.",
"The figure *surged* to an all-time high of 95%.",
"Online shopping *surged* while high-street sales collapsed.",
"There was a *surge* in applications after the university lowered its fees.",
"Energy prices *surged* by 50% in a single winter.",
"Tourist numbers *surged* once the new airport opened.",
"Sales of air conditioners *surge* every summer.",
"Interest in electric vehicles has *surged* in recent years.",
"The population of the suburb *surged* after the railway was extended.",
"A sudden *surge* in demand caused prices to spike."]},

{id:"soar", w:"soar", vn:"tăng rất mạnh, bay vọt", sec:5, sub:"📈 Động từ TĂNG", s:[
"House prices *soared* by 80% over the decade.",
"The number of smartphone users *soared* after 2010.",
"Unemployment *soared* to record levels during the depression.",
"Fuel costs *soared*, forcing many airlines to raise fares.",
"The city's population *soared* from one million to four million.",
"Profits *soared* thanks to booming overseas sales.",
"Temperatures *soared* above 40 degrees during the heatwave.",
"Demand for delivery services *soared* while restaurants were closed.",
"The figure *soared* past the previous record within months.",
"Ticket prices *soared* as the final approached."]},

{id:"go-up", w:"go up", vn:"tăng lên", sec:5, sub:"📈 Động từ TĂNG", s:[
"The price of bread *went up* by 20% in five years.",
"Rents *go up* every year in the city centre.",
"The figure *went up* steadily, from 30% to 55%.",
"Train fares *went up* faster than average wages.",
"The number of students *went up* sharply after 2012.",
"Electricity bills *went up* significantly during the winter.",
"The temperature *goes up* quickly once the sun rises.",
"Membership *went up* from 500 to over 2,000 people.",
"Taxes on cigarettes *went up*, and smoking rates fell.",
"Overall, living costs *went up* while incomes stayed flat."]},

{id:"decrease", w:"decrease", vn:"giảm", sec:5, sub:"📉 Động từ GIẢM", s:[
"The number of smokers *decreased* steadily over the period.",
"Spending on books *decreased* from 8% to 3% of the budget.",
"The figure *decreased* slightly before recovering in 2015.",
"Birth rates *decreased* in all four countries shown.",
"There was a gradual *decrease* in the amount of farmland.",
"Car accidents *decreased* significantly after the speed limit changed.",
"The rural population continues to *decrease* year by year.",
"Energy consumption *decreased* by 10% thanks to better insulation.",
"The chart shows a steady *decrease* in cinema attendance.",
"The gap between the two figures *decreased* over time."]},

{id:"decline", w:"decline", vn:"giảm, suy giảm", sec:5, sub:"📉 Động từ GIẢM", s:[
"Sales of printed newspapers *declined* sharply after 2000.",
"The manufacturing sector *declined* as services expanded.",
"The figure *declined* gradually, reaching 12% by 2020.",
"Coal production *declined* in every decade shown.",
"There was a steady *decline* in the number of farm workers.",
"The birth rate *declined* to its lowest level ever recorded.",
"Union membership *declined* from 60% to under 25%.",
"Interest in the sport has *declined* among young people.",
"The graph shows a continuous *decline* in landline use.",
"Fish stocks *declined* dramatically due to overfishing."]},

{id:"fall", w:"fall", vn:"giảm, rơi xuống", sec:5, sub:"📉 Động từ GIẢM", s:[
"The unemployment rate *fell* from 9% to 4%.",
"Prices *fell* sharply following the financial crisis.",
"The figure *fell* steadily throughout the 1990s.",
"The number of visitors *fell* to its lowest point in February.",
"There was a dramatic *fall* in the value of the currency.",
"Demand for coal *fell* as cleaner fuels became available.",
"Attendance *fell* by half when ticket prices doubled.",
"The proportion of large families *fell* considerably.",
"Profits *fell* for three consecutive years before recovering.",
"The graph shows a sharp *fall* between 2008 and 2009."]},

{id:"drop", w:"drop", vn:"giảm, sụt", sec:5, sub:"📉 Động từ GIẢM", s:[
"The figure *dropped* from 45% to 30% in five years.",
"Temperatures *drop* sharply after sunset in the desert.",
"Sales *dropped* dramatically during the recession.",
"The number of applicants *dropped* when fees were introduced.",
"There was a sudden *drop* in oil prices in 2014.",
"The birth rate *dropped* below replacement level in 2005.",
"Support for the policy *dropped* to just 20%.",
"Exports *dropped* slightly but remained above imports.",
"The company's market share *dropped* by ten percentage points.",
"The chart shows a noticeable *drop* in the final quarter."]},

{id:"dip", w:"dip", vn:"giảm nhẹ (tạm thời)", sec:5, sub:"📉 Động từ GIẢM", s:[
"Sales *dipped* slightly in the summer before recovering in autumn.",
"The figure *dipped* to 18% in 2009, then rose again.",
"There was a brief *dip* in visitor numbers during the strike.",
"Temperatures *dipped* below freezing for the first time that winter.",
"The share price *dipped* on the news but soon stabilised.",
"Attendance *dipped* in midweek and peaked at weekends.",
"Production *dipped* temporarily while the factory was modernised.",
"The graph shows a small *dip* around 2012.",
"Profits *dipped* marginally despite higher sales.",
"The unemployment rate *dipped* under 5% for a few months."]},

{id:"plunge", w:"plunge", vn:"giảm mạnh, lao xuống", sec:5, sub:"📉 Động từ GIẢM", s:[
"The value of the currency *plunged* by 30% overnight.",
"Sales *plunged* after the safety scandal became public.",
"The figure *plunged* from 60% to just 20% within a decade.",
"Temperatures *plunged* to minus fifteen degrees in January.",
"Tourist numbers *plunged* during the travel ban.",
"The company's profits *plunged* to their lowest level ever.",
"There was a dramatic *plunge* in advertising revenue.",
"House prices *plunged* when the bubble finally burst.",
"Demand for new cars *plunged* during the fuel crisis.",
"The graph shows a steep *plunge* at the start of 2009."]},

{id:"plummet", w:"plummet", vn:"lao dốc, giảm cực mạnh", sec:5, sub:"📉 Động từ GIẢM", s:[
"CD sales *plummeted* once music streaming became popular.",
"The figure *plummeted* from 80% to 25% in just five years.",
"Share prices *plummeted* on the first day of the crisis.",
"The bird population *plummeted* after the wetlands were drained.",
"Cinema attendance *plummeted* with the arrival of television.",
"Exports *plummeted* when the trade agreement collapsed.",
"The temperature *plummeted* as the storm moved in.",
"Newspaper circulation has *plummeted* over the past twenty years.",
"Bookings *plummeted* following the airline strike.",
"The chart shows the birth rate *plummeting* after 1970."]}
);
