/* ===== Phần 4: Body & Time Phrases ===== */
VOCAB.push(
{id:"looking-first", w:"Looking first at / Beginning with", vn:"Trước tiên, nhìn vào…", sec:4, sub:"Mở đầu đoạn Body", s:[
"*Looking first at* the bar chart, coal was the main source of energy in 1980.",
"*Beginning with* the United States, car ownership rose steadily throughout the period.",
"*Looking first at* men, the majority worked full-time in all age groups.",
"*Beginning with* the oldest group, only 10% used social media daily.",
"*Looking first at* food spending, this category fell from 30% to 18%.",
"*Beginning with* the year 1990, unemployment stood at 7%.",
"*Looking first at* the pie charts, housing was the largest expense in both years.",
"*Beginning with* domestic tourism, visitor numbers grew every single year.",
"*Looking first at* the line graph, sales fluctuated wildly before 2005.",
"*Beginning with* Europe, the figures show a gradual decline in birth rates."]},

{id:"regarding", w:"Regarding / In terms of", vn:"Về / Xét về", sec:4, sub:"Mở đầu đoạn Body", s:[
"*Regarding* the second chart, women spent more time on childcare than men.",
"*In terms of* population, China remained the largest country throughout.",
"*Regarding* transport, most people travelled to work by car.",
"*In terms of* energy use, industry consumed more than households.",
"*Regarding* age groups, the over-65s showed the biggest change.",
"*In terms of* overall growth, the IT sector performed best.",
"*Regarding* the remaining categories, all stayed below 10%.",
"*In terms of* exports, oil was by far the most important product.",
"*Regarding* leisure activities, watching television was the clear favourite.",
"*In terms of* cost, rail travel was more expensive than coach travel."]},

{id:"moving-on", w:"Moving on to", vn:"Chuyển sang…", sec:4, sub:"Mở đầu đoạn Body", s:[
"*Moving on to* the second graph, profits followed a similar pattern.",
"*Moving on to* women, the employment rate rose sharply after 1995.",
"*Moving on to* the other categories, entertainment saw a small increase.",
"*Moving on to* transport, spending doubled over the twenty years.",
"*Moving on to* the older age groups, internet use remained low.",
"*Moving on to* 2010, the situation had changed dramatically.",
"*Moving on to* renewable sources, wind power grew fastest of all.",
"*Moving on to* the pie chart, services dominated the economy.",
"*Moving on to* rural areas, access to healthcare improved slowly.",
"*Moving on to* the final stage of the process, the bottles are packed and shipped."]},

{id:"turning-to", w:"Turning to", vn:"Chuyển sang…", sec:4, sub:"Mở đầu đoạn Body", s:[
"*Turning to* the second chart, exports tell a very different story.",
"*Turning to* the figures for Japan, growth was much slower.",
"*Turning to* the remaining fuel types, gas overtook coal in 2000.",
"*Turning to* younger workers, part-time employment was far more common.",
"*Turning to* the table, Australia recorded the highest rainfall.",
"*Turning to* spending habits, food took a shrinking share of income.",
"*Turning to* the map of 2010, a new airport had been built in the north.",
"*Turning to* university applications, the numbers rose every year.",
"*Turning to* the least popular activities, fishing attracted only 2% of respondents.",
"*Turning to* the final decade, all three countries experienced rapid growth."]},

{id:"in-by-year", w:"In / By 2000,", vn:"Vào / Đến năm 2000", sec:4, sub:"Mở đầu đoạn Body", s:[
"*In 2000,* the majority of households still used dial-up internet.",
"*By 2000,* the factory had doubled its annual output.",
"*In 1990,* only 5% of homes owned a computer.",
"*By 2010,* this figure had risen to over 70%.",
"*In 2005,* the two lines crossed for the first time.",
"*By the year 2020,* renewable energy accounted for a third of production.",
"*In 1985,* the town had just one shopping centre.",
"*By 1995,* most of the farmland had been replaced by housing.",
"*In 2015,* smartphone ownership reached 80% among young adults.",
"*By 2050,* the elderly population is projected to double."]},

{id:"initially", w:"initially", vn:"ban đầu", sec:4, sub:"Mốc thời gian", s:[
"*Initially,* sales grew slowly, but they accelerated after 2005.",
"The figure *initially* stood at 20% before falling steadily.",
"*Initially,* most energy came from coal-fired power stations.",
"The two countries *initially* followed the same trend.",
"*Initially,* the project attracted little public interest.",
"Prices rose sharply, having *initially* remained stable.",
"*Initially,* only wealthy families could afford a car.",
"The population *initially* declined, then recovered after 1980.",
"*Initially,* the gap between the two groups was very small.",
"Demand was *initially* low but grew quickly once prices fell."]},

{id:"at-the-beginning", w:"at the beginning", vn:"lúc đầu, vào đầu (giai đoạn)", sec:4, sub:"Mốc thời gian", s:[
"*At the beginning* of the period, unemployment stood at 8%.",
"*At the beginning* of 1990, the factory employed 2,000 workers.",
"Car ownership was rare *at the beginning* of the century.",
"*At the beginning*, both figures were roughly equal.",
"*At the beginning* of the process, the raw materials are collected.",
"The town was much smaller *at the beginning* of the period shown.",
"*At the beginning* of the decade, few homes had internet access.",
"Prices were low *at the beginning* but tripled by the end.",
"*At the beginning* of the survey period, most people shopped locally.",
"The gap was widest *at the beginning* and narrowed over time."]},

{id:"afterwards", w:"afterwards", vn:"sau đó", sec:4, sub:"Mốc thời gian", s:[
"Sales peaked in 2010 and declined steadily *afterwards*.",
"The rate rose to 12% but fell back soon *afterwards*.",
"Production stopped during the war and recovered slowly *afterwards*.",
"The figure remained stable until 2005 and dropped sharply *afterwards*.",
"Prices spiked in the summer; *afterwards*, they returned to normal levels.",
"The two lines diverged in 1995 and never converged *afterwards*.",
"Attendance doubled during the festival and stayed high *afterwards*.",
"The law was introduced in 2008, and smoking rates fell *afterwards*.",
"Growth was rapid at first but slowed considerably *afterwards*.",
"The water is heated to boiling point and *afterwards* left to cool."]},

{id:"subsequently", w:"subsequently", vn:"sau đó, tiếp theo", sec:4, sub:"Mốc thời gian", s:[
"The figure peaked in 2000 and *subsequently* declined year by year.",
"Prices rose sharply and *subsequently* levelled off at around $80.",
"The company expanded rapidly and *subsequently* opened offices abroad.",
"Unemployment fell to 4% but *subsequently* climbed back to 7%.",
"The mixture is heated and *subsequently* cooled to room temperature.",
"Sales dipped in the spring and *subsequently* recovered in the autumn.",
"The area was cleared of forest and *subsequently* used for farming.",
"The trend reversed in 2012 and *subsequently* remained downward.",
"Visitor numbers doubled and *subsequently* stabilised at the new level.",
"The policy was introduced in 2015; recycling rates *subsequently* improved."]},

{id:"finally", w:"finally", vn:"cuối cùng", sec:4, sub:"Mốc thời gian", s:[
"*Finally,* the figure settled at around 65% in the last two years.",
"*Finally,* the finished products are packaged and delivered to shops.",
"After years of decline, the industry *finally* recovered in 2018.",
"*Finally,* spending on leisure showed the smallest change of all categories.",
"The two figures *finally* converged at the end of the period.",
"*Finally,* the water passes through a filter before being stored.",
"The unemployment rate *finally* returned to its pre-crisis level.",
"*Finally,* it is worth noting that the oldest group changed the least.",
"The line for gas *finally* overtook the line for coal in 2010.",
"*Finally,* both countries ended the period with similar figures."]},

{id:"over-the-period", w:"over the period / by the end of the period", vn:"trong cả giai đoạn / vào cuối giai đoạn", sec:4, sub:"Mốc thời gian", s:[
"*Over the period*, the number of cinema visits nearly tripled.",
"*By the end of the period*, the figure had reached 90%.",
"Car ownership rose dramatically *over the period* shown.",
"*By the end of the period*, coal had almost disappeared from the energy mix.",
"*Over the period*, the average family size fell from four to two children.",
"Exports grew fivefold *over the period* in question.",
"*By the end of the period*, women made up half of the workforce.",
"Temperatures rose by two degrees *over the period* covered by the graph.",
"*Over the twenty-year period*, house prices quadrupled.",
"*By the end of the period*, the two figures were almost identical."]}
);
